//Z4027500 JOB FB3,
//             Z40275,
//             NOTIFY=Z40275,CLASS=A,
//             MSGLEVEL=(1,1)
//LOGSEL  EXEC PGM=IRXJCL,
//             PARM='LOGSEL'
//SYSEXEC  DD  DSN=Z40275.TEST.REXX,DISP=SHR
//OUTDD    DD  DSN=Z40275.LOGSEL.PS,DISP=OLD
//SYSTSPRT DD  SYSOUT=*
//SYSTSIN  DD  *
/*
//